[[website]]
name = "repo.noa.re"
replicas = 3
args = ["-c", "/config/reposnake.toml"]
config = { "/config/reposnake.toml" = "reposnake.toml" }
custom-token-audiences = ["idmouse", "sts.amazonaws.com"]
emptydir-path = "/var/tmp"

[website.env]
AWS_STS_REGIONAL_ENDPOINTS = "regional"
AWS_REGION = "eu-west-2"
AWS_ENDPOINT_URL = "http://rook-ceph-rgw-berries.rook-ceph.svc"
AWS_ROLE_ARN = "arn:aws:iam:::role/reposnake"
AWS_WEB_IDENTITY_TOKEN_FILE = "/var/run/secrets/tokens/sts.amazonaws.com"
